{
 "title": "Bank Fraud Detection System",
 "description": "Real-time monitoring ",
 "tags": [
  "fraud",
  "security"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "📊 Transaction Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fraud_transactions_total{status='normal'}",
     "legendFormat": "Normal Transactions"
    },
    {
     "expr": "fraud_transactions_total{status='suspicious'}",
     "legendFormat": "Suspicious Transactions"
    }
   ]
  },
  {
   "title": "🚨 Fraud Risk Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "fraud_risk_level_percent", "legendFormat": "Risk Level" }
   ]
  },
  {
   "title": "💰 Suspicious Amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUZS" } },
   "targets": [
    { "expr": "fraud_suspicious_amount_total", "legendFormat": "Suspicious Amount" }
   ]
  },
  {
   "title": "📈 Transaction Amount Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fraud_transaction_amount_bucket",
     "legendFormat": "Amount Distribution"
    }
   ]
  },
  {
   "title": "🕒 Transactions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(fraud_transactions_total{status='normal'}[5m])",
     "legendFormat": "Normal Transactions"
    },
    {
     "expr": "rate(fraud_transactions_total{status='suspicious'}[5m])",
     "legendFormat": "Suspicious Transactions"
    }
   ]
  }
 ]
}